# Generated by Django 5.1 on 2024-10-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyFeeMaintenance',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
            ],
            options={
                'db_table': 'monthly_fee_maintenance',
            },
        )
    ]
